services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vertrigo
      - POSTGRES_DB=studentsdb
    volumes:
      - polls_pg_data:/bitnami/postgresql
    
volumes:
  polls_pg_data:
