name: Continuous Integration
on: 
  pull_request:
    branches:
      ['master']

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 20.18.2
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test
